name: Publish Release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pdm install --prod

      - name: Build package
        run: pdm build

      - name: Publish to PyPI
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: pdm publish --username __token__ --password "$PYPI_TOKEN"
